### ISSUE TITLE
No ContextFactory was found

### ISSUE THREAD

**Issue by AliYusuf95** [mfornos/humanize#42]
I tried to use the library in my android project.
I add `compile 'com.github.mfornos:humanize-slim:1.2.2'` in gradle file.
and as in usage section I write this import line `import static humanize.Humanize.binaryPrefix;` to use `binaryPrefix` function, but unfortunately I got this error:

```
java.lang.ExceptionInInitializerError
at humanize.Humanize.binaryPrefix(Humanize.java:147)
.....
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:5938)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
Caused by: java.lang.RuntimeException: No ContextFactory was found
at humanize.Humanize.loadContextFactory(Humanize.java:2922)
at humanize.Humanize.<clinit>(Humanize.java:102)
at humanize.Humanize.binaryPrefix(Humanize.java:147) 
.....
at android.os.Handler.handleCallback(Handler.java:739) 
at android.os.Handler.dispatchMessage(Handler.java:95) 
at android.os.Looper.loop(Looper.java:145) 
at android.app.ActivityThread.main(ActivityThread.java:5938) 
at java.lang.reflect.Method.invoke(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:372) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195) 
```

**Comment by larroy** [comment]
Same issue here, only when running inside spark.
